version: '3'

services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    restart:
      on-failure
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      -"443:443"
    
  wordpress:
    container_name: wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart:
      on-failure
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      wordpress: /var/www/html
    expose:
      - "9000"

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart:
      unless-stopped
    env_file:
      - .env
    volumes:
      -mariadb:/var/lib/mysql
    expose:
      - "3306"
  
volumes :
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
  mariadb:
    driver: local

networks:
  inception:
    driver: bridge 
    

