version: '3.8'

services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    restart:
      on-failure # redemarre seulement si crash
    depends_on:
      wordpress: 
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "443:443" # port exposé à la machine locale
    healthcheck:
      test: 'curl -kfsSL https://localhost:443:status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart:
      on-failure
    depends_on:
      mariadb: 
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - /home/hlesny/wordpress:/var/www/html
    expose:
      - "9000"
    healthcheck:
      test: cgi-fcgi -connect localhost:9000 /status
      interval: 5s
      timeout: 1s
      retries: 30
      start_period: 5s

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart:
      unless-stopped # redemarre tant que pas stoppé
    env_file:
      - .env
    volumes:
      - /home/hlesny/mariadb:/var/lib/mysql # path vers les dossier que l'on veut stocker sur le volume 'mariadb'
    expose:
      - "3306"
    healthcheck:
      test: mysqladmin ping --host=localhost --password="${SQL_ROOT_PASSWORD}"
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

# driver:local -> # Specifies the storage driver to use for managing the volume. The local driver is the default driver for Docker on Linux systems. It stores volumes in the /var/lib/docker/volumes/ directory on the host system
volumes :
  wordpress:
    driver: local 
  mariadb:
    driver: local

networks:
  inception:
    driver: bridge 
    

